on:
  issues:
    types: [opened]
  pull_request:
    type: [opened]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Echo some stuff
        run: |
          echo "event name '${{ github.event_name }}'"
          echo "event number '${{ github.event.issue.number }}'"
          echo "column name '${{ fromJSON('["To do", "In progress"]')[github.event_name == 'pull_request'] }}'"

      # - name: Create or Update Project Card
      #   uses: peter-evans/create-or-update-project-card@v1
      #   with:
      #     project-name: Dark theme utils
      #     column-name: ${{ fromJSON('["To do", "In progress"]')[github.event_name == 'pull_request'] }}
      #     issue-number: ${{ github.event.number }}